# Site settings
title: Annuaire des organisations libérées
description: "Annuaire des organisations et entreprises libérées ayant documenté leur fonctionnement"
baseurl: ""
url: "http://organisationsliberees.org/"
twitter_username: orgasliberees
github_username:  organisationsliberees
include: [".htaccess"]
exclude: ["Makefile", "bin", "LICENSE"]
gems:
  - jekyll-redirect-from
# Build settings
markdown: kramdown
permalink: pretty
